# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
python:
    - 3.6
    - 3.7
    - 3.8

# what branches should be evaluated
branches:
    only:
        - master

# list of commands to run to setup the environment
install:
    - pip install coverage
    - pip install coveralls
    - pip install flake8
    - pip install -r requirements.txt

# the actual commands to run
script:
    - coverage run -m unittest discover EDA-assistant

# generate a coverage report to send to back to user
after_success:
    - coverage report
    - coveralls
